version: '3.8'
services:
  api:
    build: ./Backend
    container_name: api
    ports:
      - '8080:8080'

  front:
    build: ./frontend
    container_name: front
    ports:
        - '3000:3000'
    depends_on:
      - api